LinterJustSayNoProvider = require './linter-just-say-no-provider'

module.exports =
  config:
    hedgeWords:
      type: 'array'
      default: [
        'a bit'
        'a little'
        'a tad'
        'a touch'
        'about'
        'almost'
        'apologize'
        'apparently'
        'appear'
        'around'
        'basically'
        'bother'
        'could'
        'does that make sense'
        'effectively'
        'evidently'
        'fairly'
        'generally'
        'hardly'
        'hopefully'
        'I think'
        'in general'
        'just'
        'kind of'
        'largely'
        'likely'
        'mainly'
        'may'
        'maybe'
        'might'
        'more or less'
        'mostly'
        'nearly'
        'overall'
        'partially'
        'partly'
        'perhaps'
        'possibly'
        'presumably'
        'pretty'
        'probably'
        'quite clearly'
        'quite'
        'rather'
        'really quite'
        'really'
        'seem'
        'seemed'
        'seems'
        'some'
        'sometimes'
        'somewhat'
        'sorry'
        'sort of'
        'suppose'
        'supposedly'
        'think'
        'try'
        'trying'
        "I'm no expert"
      ]
      items:
        type: 'string'

  activate: ->
    console.log 'activate linter-just-say-no' if atom.inDevMode()
    require('atom-package-deps').install 'linter-just-say-no'

  provideLinter: -> LinterJustSayNoProvider
